language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  - pip

# Use unstable R packages
addons:
  apt:
    sources:
      - sourceline:
          "deb http://ftp.us.debian.org/debian unstable main contrib non-free"
        key_url:
          "https://ftp-master.debian.org/keys/archive-key-10.asc"
    update: true
    # Packages needed to build diveMove's dependencies
    packages:
      - build-essential
      - gcc
      - g++
      - gfortran
      - liblapack-dev
      - libblas-dev
      - r-base
      - r-base-dev

before_install:
  - sudo Rscript -e 'install.packages("diveMove")'

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest -v skdiveMove/tests

after_success:
  - pip install .["docs"]
  - make -C docs/ html
  - touch docs/build/html/.nojekyll

jobs:
  include:
    - stage: GitHub Pages
      python: "3.8"
      script: skip
      deploy:
        provider: pages:git
        verbose: true
        token: $GITHUB_TOKEN
        edge: true
        local_dir: ./docs/build/html
        keep_history: false
        on:
          branch: master
        target_branch: gh-pages
