# Build on supported Pythons
#
# Closely watch version references for actions!

name: Python build

on: [push, pull_request]

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      PY_LATEST: 3.9

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up R (release)
        # They tell us to use master (ambiguously)
        uses: r-lib/actions/setup-r@v1

      - name: Install system requirements
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Install diveMove
        run: |
          install.packages('diveMove')
        shell: Rscript {0}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          python -m pip install -r requirements.txt

      - name: Build binary wheel and source tarball
        run: |
          python setup.py build sdist bdist_wheel
          twine check dist/*

      - name: Test and coverage
        run: |
          python -m pip install --upgrade pytest coverage
          coverage run --branch -m pytest skdiveMove
          coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        if: matrix.python-version == env.PY_LATEST
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Build Sphinx docs
        if: matrix.python-version == env.PY_LATEST
        run: |
          sudo apt-get install ffmpeg
          python -m pip install .['docs']
          make -C docs/ html
          touch docs/build/html/.nojekyll

      - name: Upload products
        uses: actions/upload-artifact@v2
        if:
          (matrix.python-version == env.PY_LATEST) &&
          startsWith(github.ref, 'refs/tags')
        with:
          name: dist-pkg
          path: |
            dist
            docs/build

  deploy:
    # No matrix here, so just test for tag. Runs on every tag, so artifact
    # expected from "build"
    name: Deploy to GitHub Pages
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Download products
        uses: actions/download-artifact@v2
        with:
          name: dist-pkg

      - name: Publish GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
